select 
    SHOPNUMBER,
    CITY,
    ADDRESS,
    SUM(QTY) AS SUM_QTY,
    SUM(PRICE::INT * QTY) AS SUM_QTY_PRICE
from 
    SALES 
    JOIN GOODS ON SALES.DATE = '02.01.2016'
                  AND SALES.ID_GOOD = GOODS.ID_GOOD
    JOIN SHOPS USING(SHOPNUMBER)
GROUP BY 
    SHOPNUMBER, CITY, ADDRESS;