SELECT DISTINCT
    SHOPNUMBER,
    CITY,
    ADDRESS,
    SUM(QTY) OVER w AS SUM_QTY,
    SUM(PRICE::INT * QTY) OVER w AS SUM_QTY_PRICE
FROM
    SALES 
    JOIN GOODS ON SALES.DATE = '02.01.2016'
                  AND SALES.ID_GOOD = GOODS.ID_GOOD
    JOIN SHOPS USING(SHOPNUMBER)
WINDOW w AS (PARTITION BY SHOPNUMBER);
