SELECT 
    SALES.DATE AS DATE_,
    SALES.SHOPNUMBER AS SHOPNUMBER,
    CATEGORY,
    LAG(SUM(PRICE::INT * QTY)) OVER w AS PREV_SALES
FROM
    SALES
    JOIN SHOPS ON CITY = 'СПб' 
                  AND SALES.SHOPNUMBER = SHOPS.SHOPNUMBER
    JOIN GOODS USING(ID_GOOD)
GROUP BY
    SALES.DATE,
    SALES.SHOPNUMBER,
    CATEGORY
WINDOW w AS (
    PARTITION BY SALES.SHOPNUMBER, CATEGORY
    ORDER BY TO_DATE(SALES.DATE, 'DD.MM.YYYY')
)
ORDER BY
    TO_DATE(SALES.DATE, 'DD.MM.YYYY'),
    SHOPNUMBER,
    CATEGORY;